### ISSUE TITLE
http not listening

### ISSUE THREAD

**Issue by mightywomble** [bastienwirtz/homer#216] opened 2021-04-28 10:32 UTC
Having run 
`docker run -d -p 8080:8080 -v /opt/docker/homer:/www/assets --restart=always b4bz/homer:latest`

the container starts

`CONTAINER ID   IMAGE               COMMAND                  CREATED         STATUS         PORTS                                       NAMES
e4c28c22e8a0   b4bz/homer:latest   "/bin/sh /entrypoint…"   7 seconds ago   Up 5 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   determined_antonelli`

The firewall port is open 

The webpage didn't load so I had a look at docker logs which sits at

`darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.`

if i restart the container I get

```
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:8080/
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
```
Which seems as though there is something stopping the httpd server start

Any suggestions?

```
 ls /opt/docker/homer/ -l
total 24
-rw-r--r--. 1 911 911 1263 Apr 28 11:25 additionnal-page.yml.dist
-rw-r--r--. 1 911 911 2908 Apr 28 11:25 config.yml
-rw-r--r--. 1 911 911 2908 Apr 28 11:25 config.yml.dist
-rw-r--r--. 1 911 911 2010 Apr 28 11:25 config.yml.dist.sample-sui
-rw-r--r--. 1 911 911  176 Apr 28 11:25 custom.css.sample
drwxr-xr-x. 2 911 911  150 Apr 28 11:25 icons
-rw-r--r--. 1 911 911  655 Apr 28 11:25 manifest.json
drwxr-xr-x. 2 911 911   43 Apr 28 11:25 tools
```

**Comment by JenswBE** [comment] 2021-06-04 18:50
I just hit the same issue with the official docker-compose file. Seems a tty should be assigned when running.
E.g. `-t` or `--tty` when running with `docker` or `tty: true` when running with Docker Compose.

I'll create a PR to update the official examples.

**Comment by JenswBE** [comment] 2021-06-04 19:02
While implementing the fixes, I actually noticed the tty assignment only impacts printing of the line `listening on: http://0.0.0.0:8080/`. Not being able to reach Homer was due to a missing network assignment to my reverse proxy.

For your specific issue I might recommend trying to reproduce with another container like Nginx or Apache. This way you can at least check if it's Homer or your general setup (firewall, NAT, ...) giving issues.

**Comment by bastienwirtz** [comment] 2021-09-26 08:29
Hi there, 

Sorry for the late reply, @mightywomble are you still having the issue ? If yes, can you provide more information about the web page not loading ? Is it working with a curl ? is the docker listening correctly ? (maybe a telnet test?) Do you have any error un the browser web console ?

**Comment by mightywomble** [comment] 2021-09-26 10:12
I moved on, found a working solution


David Field
http://tech.davidfield.co.uk

**Comment by bastienwirtz** [comment] 2021-09-26 11:38
All right :+1: 
I'm closing this one.

**Closed by bastienwirtz** 2021-09-26 11:38 UTC
