### ISSUE TITLE
Not redirecting to Authelia after timeout

### ISSUE THREAD

**Issue by bodycount28** [bastienwirtz/homer#226] opened 2021-06-03 16:32 UTC
I just started using Homer and liking so far, thanks for the great work.  I have it sitting behind a Traefik proxy, being protected by Authelia 2FA and set to timeout after 10 min of browser inactivity.  Upon expiration and refreshing the page, instead of automatically redirecting back to the Authelia authentication page Homer throws an offline message:

![image](https://user-images.githubusercontent.com/85305683/120679097-a71aa800-c44d-11eb-85b8-691bb72c9c45.png)

Is this a bug or a missing feature that can be requested?

In order to get back in I have to open a new tab with Authelia and login, then refresh Homer.

Thanks in advance...

**Comment by rucknapucknavitz** [comment] 2021-06-03 17:48
I came here for the same issue, to see it was posted just an hour ago.
I'm using Authelia behing Traefik2, and all my authentication labels for Homer are configured exactly the same as other containers - which do properly re-route after a timeout. After a timeout, I need to access one of those containers first or straight to authelia.mydomain.com to become authenticated, otherwise I get the same error as @bodycount28 

Any help appreciated, and glad to help troubleshoot if pointed in the right direction.

**Comment by adyanth** [comment] 2021-06-07 08:54
Check #229 similar issue for a different use case.
For your this, I guess if the connectivity check status code is 3xx or 401/403, a page reload with `location.href = location.href` should be done to correctly redirect after timeout.

**Comment by fbartels** [comment] 2021-07-14 19:32
I think its worth checking out if https://github.com/bastienwirtz/homer/pull/186 fixes this issue for the other posters.

**Comment by Zutart** [comment] 2021-07-19 18:53
Hey @fbartels,

Unfortunately, it doesn't appear as if the issue is resolved. I pulled down the latest docker image from b4bz/homer and recreated the container. I still get the error message from the original post and I'm unable to get back to the Authelia authorization screen even if I do a hard refresh (doing this in Chrome, Win 10).

**Comment by zotabee** [comment] 2021-09-15 15:40
Seems still broken even after pull/186 (using authelia/authelia:latest) as of yesterday build.

**Comment by bastienwirtz** [comment] 2021-09-26 08:19
Hi there, 

Lots of issues open on this topic, I'm centralizing the discussions on the most recent one (#232 ) and closing the duplicates. I will work on that asap.

**Closed by bastienwirtz** 2021-09-26 08:19 UTC
