### ISSUE TITLE
Homer shows - You're offline friend - error

### ISSUE THREAD

**Issue by kkoshelev** [bastienwirtz/homer#236] opened 2021-06-19 22:41 UTC
I use vouch proxy for authentication and when credentials expire instead of redirect to auth page Homer shows "You're offline friend" error.

Nginx reverse proxy config:

```code
location / {
    proxy_pass http://10.1.10.123:80/;  # homer port
    proxy_set_header Host $http_host; # pass original host
}
```

The same config works with any other app but Homer. I suspect that has something to do with caching.

**Comment by chris-si** [comment] 2021-06-21 08:44
The same behavior occurs with Traefik as reverse proxy and Authelia as auth server. There is no redirect happening after session/token expiration or a manual logout.

**Comment by Zutart** [comment] 2021-06-21 23:41
I can confirm the same behavior behind Aurelia

**Comment by mguaylam** [comment] 2021-06-24 15:38
I have the same issue with Authelia. I read there was some work on it but ultimately, I think it’s a caching issue as well.

**Comment by Zutart** [comment] 2021-06-24 15:44
Yeah @mguaylam looks like this is the same as issue #226 (apologies for not seeing that first initially). I finally figured out that a hard reload (Cntl+Shift+R in Chrome) gets me back to the authentication window properly. Unfortunately unable to do the same yet on mobile, so the only workaround I've found is to either go to the Authelia domain directly to authenticate or just load into another service behind Authelia - both get your session back online and load Homer correctly after.

Hopeful there's a fix coming as I'm really loving this dashboard (and the ability for me to potentially automate services getting added to it by watching the docker labels).

**Comment by mguaylam** [comment] 2021-06-24 16:05
Yeah that’s what i’m forced to as well. To go manually to the /auth/ page of Authelia. Only issue, I can’t do that on iOS. The web app won’t allow that.

**Comment by fbartels** [comment] 2021-07-14 19:31
I think its worth checking out if https://github.com/bastienwirtz/homer/pull/186 fixes this issue for the other posters.

**Comment by jboesh** [comment] 2021-08-01 10:40
I still have the same problem.
could the message You're offline friend, not disappear completely? I don't need to know through Homer whether I'm offline, I notice that in a different way.
Every time I look at Homer, sit on another tab for 2 seconds and back again, I get that message.
Starting to get pretty annoying

thanks in advance

**Comment by IosifZ** [comment] 2021-08-31 07:02
> Yeah @mguaylam looks like this is the same as issue #226 (apologies for not seeing that first initially). I finally figured out that a hard reload (Cntl+Shift+R in Chrome) gets me back to the authentication window properly. Unfortunately unable to do the same yet on mobile, so the only workaround I've found is to either go to the Authelia domain directly to authenticate or just load into another service behind Authelia - both get your session back online and load Homer correctly after.
> 
> Hopeful there's a fix coming as I'm really loving this dashboard (and the ability for me to potentially automate services getting added to it by watching the docker labels).

I have the exact same issue. Ctrl+Shift+R solves the issue, but unfortunately there is no way to accomplish this on my mobile. Any news on this one?

**Comment by zotabee** [comment] 2021-09-15 15:40
Seems still broken even after pull/186 (using authelia/authelia:latest) as of yesterday build.

**Comment by virtadpt** [comment] 2021-09-22 23:00
#186 isn't working for me, either.
Built from Git commit d489f6ef87763099abdefd197f1d973a78f59883, behind HTTP basic auth.  Debugging console shows that /assets/config.yml can't be pulled down because a 401 error was received from the server (after I authenticated and the rest of Homer was loaded).

**Comment by bastienwirtz** [comment] 2021-09-26 08:09
Hi there !

I'm closing this one because it's a duplicate of #226. I will work on that asap!

**Closed by bastienwirtz** 2021-09-26 08:09 UTC
