### ISSUE TITLE
2x Custom Services Do Not Work

### ISSUE THREAD

**Issue by Ashkaan** [bastienwirtz/homer#520] opened 2022-10-09 23:22 UTC
Tautulli and Proxmox fail to connect.  I'm fairly sure that I have configured them correctly.

On the other hand, Prowlarr, Radarr, and Sonarr each work perfectly, so we can rule out a lot of potential networking issues.

I'm running Homer on Docker on a Synology NAS.  Tautulli is also a Docker on the Synology NAS.  Proxmox is on a bare metal server.

Here are my configs:

`      - name: "Tautulli"
        logo: "assets/images/tautulli.png"
        type: "Tautulli"
        # tag: "network"
        # tagstyle: "is-success"
        keywords: "app, media"
        url: "http://10.1.0.25:8181" (I've also tried 127.0.0.1 since it's the same server)
        endpoint: "http://10.1.0.25:8181"
        apikey: "<secret>"
        target: "_blank"`

`      - name: "Proxmox-1A"
        logo: "assets/images/proxmox.png"
        type: "Proxmox"
        # tag: "network"
        # tagstyle: "is-success"
        keywords: "server"
        url: "https://10.1.0.30:8006"
        node: "10.1.0.30"
        warning_value: 50
        danger_value: 80
        api_token: "PVEAPIToken=root@pam!homer=<secret>"
        target: "_blank"`

Thank you

**Comment by bastienwirtz** [comment] 2022-10-10 06:09
Hi @Ashkaan, 
Do you have any error in the web console ? Did you check the [troubleshooting guide](https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md) (especially about CORS)?

**Comment by jimbytes** [comment] 2022-10-10 13:10
Hi,
I almost got it working. Th service show some data but all with 0 as values. After couple of seconds, it shows Error loading informations. 

In the browser log, I can see error : Failed to load resource: cannot parse response https://servername.domainname.com/api2/json/nodes/servername/status.

When I tried to browse manually this URL, I can see all data.

**Comment by Ashkaan** [comment] 2022-10-10 17:54
Hey there,

The logs seem to be empty:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/5667978/194925952-678576c1-a41b-4db4-811f-90278f2e4ce0.png">

Also, I tried many things in the config, including adding the node name:

`      - name: "Proxmox-1A"
        logo: "assets/images/proxmox.png"
        type: "Proxmox"
        <<: *hardware
        keywords: "server"
        url: "https://10.1.0.30:8006"
        node: "proxmox-1a"
        warning_value: 50
        danger_value: 80
        api_token: "PVEAPIToken=root@pam!homer=<secret>"
        target: "_blank"`

Also, any idea about Tautulli?  Again, no logs.  Or, maybe I'm looking at the wrong logs?

**Comment by luixal** [comment] 2022-10-10 18:38
Let's make some troubleshooting. First, I had some CORS problems when querying Proxmox and had to put it behind a proxy so the proxy returns the right CORS headers (I used Nginx Proxy Manager with some custom nginx config, I can provide it for you).

Please, open chrome's console and enter this commands:

```js
const data = await fetch(`<your-proxmox-server>/api2/json/nodes/<your-node-name>/status`, { headers: { 'Authorization': 'PVEAPIToken=root@pam!<your-api-key-name>=<your-api-key-secret> } });
console.log(await data.json());
```

and paste the logs here and let's see if something interesting appears.

**Comment by Ashkaan** [comment] 2022-10-10 18:43
Ok, I hope I did this correctly:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/5667978/194932679-4cd8714f-028e-465a-abf3-4fe9843af9c3.png">

Logs remain unchanged.

**Comment by tobidemski** [comment] 2022-10-10 19:16
> Let's make some troubleshooting. First, I had some CORS problems when querying Proxmox and had to put it behind a proxy so the proxy returns the right CORS headers (I used Nginx Proxy Manager with some custom nginx config, I can provide it for you).
> 
> Please, open chrome's console and enter this commands:
> 
> ```js
> const data = await fetch(`<your-proxmox-server>/api2/json/nodes/<your-node-name>/status`, { headers: { 'Authorization': 'PVEAPIToken=root@pam!<your-api-key-name>=<your-api-key-secret> } });
> console.log(await data.json());
> ```
> 
> and paste the logs here and let's see if something interesting appears.

There is a typo in the auth header (missing single quote at the end).

**Comment by Ashkaan** [comment] 2022-10-10 19:22
Also, I am running this through a reverse proxy, so if you have a header you'd like me to pass, please share it and I'll put it.

**Comment by tobidemski** [comment] 2022-10-10 19:40
I got it to work after a while (cors issues, api token issues etc.)

Would be nice to know which permissions do i really have to grant the api token. (Should we document in the service section)
I created a new role with Privileges "Sys.Audit (Get get the node stats), VM.Audit (to read the vm count)
After this i set the permission to / with the new role for my api token.


Im not an expect in nginx and cors but I set this in my nginx proxy manager for the location /api2:

if ($request_method = 'OPTIONS') {
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    
    add_header 'Content-Type' 'text/plain; charset=utf-8';
    add_header 'Content-Length' 0;
    return 204;
}

if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
}

Side note for the homer config: Do not set a subtitle otherwise you dont see the stats. (I just failed here too)

**Comment by Ashkaan** [comment] 2022-10-10 19:43
Darn, that didn't seem to work for me:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/5667978/194941122-8e26961b-2b18-417a-8841-32bd46b8fb16.png">

Also, I definitely don't have a subtitle.

**Comment by tobidemski** [comment] 2022-10-10 19:45
Do you have
`proxy:
  useCredentials: false`

set in homer config?

I have this set to false

**Comment by tobidemski** [comment] 2022-10-10 19:56
> request_method

Do you have this set only for request_method = OPTIONS?

**Comment by Ashkaan** [comment] 2022-10-10 20:00
> Do you have `proxy: useCredentials: false`
> 
> set in homer config?
> 
> I have this set to false. Not sure if this is relevant. But if i set this to true all my calls will fail

Yep, I do.

> Do you have this set only for request_method = OPTIONS? Because content length shouldnt be 0 if not OPTIONS

I don't know how to do that.  I'm thinking that this should work even without a reverse proxy, no?

**Comment by tobidemski** [comment] 2022-10-10 20:24
> > Do you have `proxy: useCredentials: false`
> > set in homer config?
> > I have this set to false. Not sure if this is relevant. But if i set this to true all my calls will fail
> 
> Yep, I do.
> 
> > Do you have this set only for request_method = OPTIONS? Because content length shouldnt be 0 if not OPTIONS
> 
> I don't know how to do that. I'm thinking that this should work even without a reverse proxy, no?

Guess it's not working without a reverse proxy because you need to set the CORS. By default an application usually disallow all origins and either the application (in this case proxmox) allow to set an origin or you have to use a proxy to "inject" it.

**Comment by Ashkaan** [comment] 2022-10-10 20:28
How can I do that with my Reverse Proxy?

I'm using Synology DSM.  I can put a "header" and a "value".  I don't think it can do IF/Then.

**Comment by tobidemski** [comment] 2022-10-10 20:33
I guess its not possible with Synology because they wrap the hole proxy software with a custom gui and many parts are missing here. If you have docker on your Synology you could install https://nginxproxymanager.com/ and use this as your primary proxy.
Of course you will have to move all stuff over and its a bit headache but its worth :D I did the same

**Comment by Ashkaan** [comment] 2022-10-10 20:42
Ahh, bummer.  Are you guys open to adjusting the app so that it can work without a proxy?

**Comment by Ashkaan** [comment] 2022-10-10 20:42
I guess at this point, it's a feature request.

**Comment by tobidemski** [comment] 2022-10-10 20:44
Its not a limitation of homer. Its the limitation of each individual application.

**Comment by Ashkaan** [comment] 2022-10-10 20:51
It's interesting that Tautulli also fails to function.  However, the "arr" apps work great!

**Comment by shenhong96** [comment] 2022-10-11 02:29
I can confirm that after adding the header into nginx proxy manager and the dashboard rendered the infos no problem. Thanks! :)

**Comment by bastienwirtz** [comment] 2022-10-11 07:39
Yeah the CORS stuff sucks (for our own good tho). Sadly Homer, as a simple static client side app, cannot do anything about it.
I intend to improve that by adding an optional "cors proxy" container (kind of) to deal with that which can also be configured to add an auth token to a request (to avoid exposing auth token client side) at some point. Just have to take some time to work on it!

**Comment by luixal** [comment] 2022-10-11 07:43
Hi,

Yes, as Homer is only a frontend app (no backend services) all queries to APIs are donde from the browser and many webapps/services/whatever don't allow to set CORS header so the use of a proxy is mandatory. It has been asked in Proxmox forums and proxmox devs tell you to put a reverse proxy upfront (and it's the best choice from my pov).

If it's not in the documentation, I can put a custom recipe in the docs to make this config using NGINX Proxy Manager (which is the simplest way I've found to do this). @bastienwirtz just tell me if you want me to add this to the docs.

As for this custom service, i'll include some changes:

- Do not show zero values, but a "Loading..." message while waiting for proxmox response (don't know way, but it's way to slower in responding when cors problem happens).
- Try to identify the CORS error and show it on the error message (or at least the error code).
- Maybe the modal on an icon click with the list of VMs and its stats, but i will only do this if @bastienwirtz is ok with it :)
- Add needed permissions for the API token to the docs as @tobidemski pointed out.

About the subtitle having priority over the stats, I kept it that way in case someone prefers ti have a subtitle. This way you can add/remove it according to your needs.

PS: in the proxy, this custom service only makes GET queries, no POST config needed. Not sure about the OPTIONS right now, but I think they were needed, i'll test it.

PS2: here's a possible solution for people using Synology's reverse proxy. It's a year old but i don't have this device to test it.
 https://www.reddit.com/r/synology/comments/px5mrt/adding_cors_headers_to_builtin_nginx_reverse_proxy/

**Comment by luixal** [comment] 2022-10-11 17:30
As error handling with fetch is hell, errors will be logged to developers console.

The modal thing won't be implemented as bulma modals seem to have some kind of problems in this project; the modal shows fine but, when moving the mouse, it gets buggy.

I'll send the PR with doc updates, the loading message and animated icon and error icon.

**Comment by jordantrizz** [comment] 2022-10-12 18:46
> I'm using Synology DSM. I can put a "header" and a "value". I don't think it can do IF/Then.

You won't be able to override cors within Synology's UI, you have to change the Portal.mustache file within your Synology. This article will help.

https://www.reddit.com/r/synology/comments/px5mrt/adding_cors_headers_to_builtin_nginx_reverse_proxy/

**Closed** 2022-10-13 19:51 UTC

**Comment by Ashkaan** [comment] 2022-10-14 05:53
Have you guys figured out how to do this with Traefik in Kubernetees?  I ditched the Synology and I still can't get this:

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "*"
    accessControlAllowCredentials: true

**Comment by ZanzyTHEbar** [comment] 2022-12-11 00:56
I am also trying to get this working with `traefik`. No luck yet. 
I've tried every header combination i can think of. 


I am running Homer using docker compose behind `traefik` - this works fine. I also have proxmox behind the reverse proxy, but i get this error:
```txt
Access to fetch at 'https://proxmox.mydomain.com/api2/json/nodes/dragon/status' from origin 'https://dashboard.mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM10861:1              
GET https://proxmox.mydomain.com/api2/json/nodes/dragon/status net::ERR_FAILED
(anonymous) @ VM10861:1
VM10861:2 Uncaught TypeError: Failed to fetch
    at <anonymous>:1:20
```

**Comment by lexathon** [comment] 2025-02-27 13:46
I spent hours last night trying to figure out how to get past cors with nginx proxy manager and tried loads of different options. Eventually came across this... It's a change to the Proxmox proxy service itself, but has worked perfectly.

https://forum.proxmox.com/threads/api-calls-from-webapp.81479/post-520486

after making the changes in Proxmox (probably best over ssh), relaunch the pveproxy service:-
systemctl restart pveproxy.service
