### ISSUE TITLE
Error: : [object ReadableStream]

### ISSUE THREAD

**Issue by damomato** [bastienwirtz/homer#230] opened 2021-06-09 02:47 UTC
Hi, this error is popping up. I installed using Docker on DSM 6.2.4 and haven't made any changes to the config file.

Docker-compose
```
  homer:
    image: b4bz/homer:latest
    container_name: homer
    environment:
      - PUID=1026
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - ./homer:/www/assets
    ports:
      - 8484:8080
    restart: unless-stopped
```

![image](https://user-images.githubusercontent.com/85538685/121284427-69b39000-c90f-11eb-810f-cf2780bbb87d.png)

Anyone have any suggestions to fix?

Thanks

**Comment by CCCoderDE** [comment] 2021-06-13 12:09
Double check that the config.yml exists in the correct location. If that is the case, check that your browser is targeting the right path (using dev console in browser)

**Comment by rgriffogoes** [comment] 2021-06-14 00:56
I've just installed the docker version of homer and the automatic example was giving me that error when clicking the "another page!" link on menu.

As CCCoderDE suggested, I looked at dev console in browser and was able to see that Homer was looking for the `additionnal-page.yml` file which was not there - once I renamed the `additionnal-page.yml.dist` file, it worked fine!

**Comment by bhistoricalservices** [comment] 2021-06-14 01:27
Can confirm this just worked for me as well.

**Comment by damomato** [comment] 2021-06-14 07:35
> I've just installed the docker version of homer and the automatic example was giving me that error when clicking the "another page!" link on menu.
> 
> As CCCoderDE suggested, I looked at dev console in browser and was able to see that Homer was looking for the `additionnal-page.yml` file which was not there - once I renamed the `additionnal-page.yml.dist` file, it worked fine!

What exactly do you change? I'm not great with dev console and can't seem to find where this is. I may need step by step instructions.

**Comment by fleyd-1** [comment] 2021-11-17 14:37
Hi everyone,

I have Synology Ds 720+ with docker and portainer, when i try to install Homer via Portainer templates i get the same error as described above.

![image](https://user-images.githubusercontent.com/64219933/142220432-fa2305fd-074c-4cba-bf96-dc4566f6ed4d.png)

Logs in Portainer as below:


```
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.

listening on: http://0.0.0.0:8080/

1637159550 172.17.0.1 "GET /" 304 136 "http://192.168.1.118:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159550 172.17.0.1 "GET /assets/config.yml" 403 406 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159550 172.17.0.1 "HEAD /?alive" 200 219 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159550 172.17.0.1 "GET /assets/icons/favicon-32x32.png" 403 419 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159550 172.17.0.1 "GET /assets/icons/favicon-16x16.png" 403 419 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159568 127.0.0.1 "GET /" 200 3114 "" "Wget"

1637159599 127.0.0.1 "GET /" 200 3114 "" "Wget"

1637159628 172.17.0.1 "HEAD /?alive" 200 219 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159630 172.17.0.1 "GET /" 304 136 "http://192.168.1.118:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159630 172.17.0.1 "GET /assets/config.yml" 403 406 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159630 172.17.0.1 "HEAD /?alive" 200 219 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159630 127.0.0.1 "GET /" 200 3114 "" "Wget"

1637159630 172.17.0.1 "GET /assets/icons/favicon-32x32.png" 403 419 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159630 172.17.0.1 "GET /assets/icons/favicon-16x16.png" 403 419 "http://192.168.1.118:8902/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

1637159661 127.0.0.1 "GET /" 200 3114 "" "Wget"

1637159693 127.0.0.1 "GET /" 200 3114 "" "Wget"
```

Anyway i can fix this?

Sorry to use this thread but to me seems the problem is the same....

**Comment by AlexObukhoff** [comment] 2021-11-23 19:55
Same result on Synology DS 918+

**Comment by fbartels** [comment] 2021-11-24 08:42
> "GET /assets/config.yml" 403

403 means that the access to the url was denied by the webserver. Do you have a reverse proxy with authentication in front of Homer?

**Comment by fleyd-1** [comment] 2021-11-24 12:24
Hi, in my case no reverse proxy. 
I Just installed from Portainer templates and accessed it from internal IP + port.

**Comment by AlexObukhoff** [comment] 2021-11-24 14:14
I resolve this problem by the nest step:
go to the shell in docker container (sh)
```shell
# cd /www
# chmod 777 assets assets/icons assets/tools 
```

**Comment by fleyd-1** [comment] 2021-11-24 14:33
Hi Alex,

I think your suggestion worked, i dont see the error message anymore. I will now start adding links.

Thanks for the help!

**Comment by ykktrcb7** [comment] 2022-04-12 17:26
For me it happens on Firefox for android while it is always working on the laptop. Anyone has ideas?
I tried chmod 777 and no change.

**Comment by tomdaley92** [comment] 2022-04-16 14:32
Not sure what's going on here but with the default docker configuration with `/www/assets` mounted to my host at `~/.diesel/homer/production/config/` Homer was looking for the `additional-page.yml` so I just copied `additional-page.yml.dist`

![image](https://user-images.githubusercontent.com/12147036/163678982-295b8616-3312-4b8d-9fbb-c09dcf7c2a81.png)

![image](https://user-images.githubusercontent.com/12147036/163678913-93b02c43-5b62-443c-b0ed-cf9b9f223cbf.png)

Now it's working just fine:
![image](https://user-images.githubusercontent.com/12147036/163678945-3608b7a8-27ae-4e8f-ba01-d95a8b4592f4.png)

I've hardly read through the documentation, but what are these *yml.dist extensions? It seems they containt the exact same thing as the just *.yml extensions?

**Comment by bastienwirtz** [comment] 2022-07-15 20:21
@tomdaley92 `.dist` files are just example file which can be use a base for your config or can just be deleted. 

I just removed the reference from the additional-config.yml from the example config.yml file, this should be fixed !

**Closed by bastienwirtz** 2022-07-15 20:21 UTC

**Comment by woloss** [comment] 2022-10-15 16:17
Had same issue, but 413 error for `config.yml` due to oauth2-proxy wildcard cookie, even thought I didn't enable auth for dashboard.
Fixed on reverse proxy with this
```
proxy_hide_header Set-Cookie;
proxy_ignore_headers Set-Cookie;
proxy_set_header Cookie "";
```
